services:
  db:
    image: postgres:16-alpine
    container_name: santee-db
    environment:
      POSTGRES_DB: healdrive
      POSTGRES_USER: sante_user
      POSTGRES_PASSWORD: "SteNad2026@"
    ports:
      - "54325:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sante_user -d healdrive"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: santee-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/healdrive
      SPRING_DATASOURCE_USERNAME: sante_user
      SPRING_DATASOURCE_PASSWORD: "SteNad2026@"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: santee-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  postgres_data:
