# ============================================================
# HealDrive — Spring Boot 3 Configuration
# ============================================================

# DATASOURCE — PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/healdrive
spring.datasource.username=sante_user
spring.datasource.password=SteNad2026@
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Paris

# JACKSON (JSON)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Europe/Paris

# SERVEUR
server.port=8081
server.servlet.context-path=/api

# LOGGING
logging.level.root=INFO
logging.level.com.healdrive=DEBUG
logging.level.org.hibernate.SQL=DEBUG
